### ISSUE TITLE
allow more lenient schemas

### ISSUE THREAD

**Issue by SlothOfAnarchy** [khenderick/zfs-snap-manager#26]
`50d1y` is currently not a valid schema. One also has to define zero-sized buckets (`50d0w0m1y`) for the tool to work in the current state.

**Comment by stevleibelt** [comment]
Hey, I hope my feature request is meaning the same like the one from @SlothOfAnarchy.

I ran into the issue that one dataset never got a snapshot. After playing around with it, I've figured out that I've configured the `schema` value wrong since almost day one.
The snapshot was never done since for that dataset, I've just configured `7d` as value of `schema`.
My other configurations where partly working (but working good enough) so that a snapshot was created but none of them where deleted. After configuring the `schema` right like `7d0w0m0y`, everything was working as expected.

After this explenation, finally the feature request. For each value part of the `schema`, could you check if it exists and if not replace it with a default value of `0`?

I bet my feature request solves half of @SlothOfAnarchy feature requests problem. That is the reason I've put it in here.

Thanks for your work so far. Your `zfs-snap-manager` really ease up my life :).

**Comment by khenderick** [comment]
I'm closing this issue as I unfortunately don't have the time anymore to maintain ZFS Snapshot Manager. I would like to point you towards the awesome tool [zrepl](https://zrepl.github.io/) which has nearly all of ZFS Snapshot Manager's features and much more.

In any case, thanks for being a part of this community.
